[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-its-done"

[context.deploy-preview.environment]
  NETLIFY_VERBOSE = "true"

[[redirects]]
  from = "/cuties"
  to = "https://www.petsofnetlify.com"
