[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NETLIFY_VERBOSE = "true"

[context.deploy-preview.environment]
  NETLIFY_VERBOSE = "true"

[context.branch-deploy.environment]
  NETLIFY_VERBOSE = "debug"